### ISSUE TITLE
Throughput test mode always give the result 0

### ISSUE THREAD

**Issue by hoangducnghi2207** [atomic14/esp-now-range-test#1]
Hello sir, I tried to use your test in Throughput test mode to test my device, but it always shows the result like this
![image](https://user-images.githubusercontent.com/56064934/145676018-829d37de-1dea-4417-aac3-f0b7f6a52a39.png)
Could you help me to explain and solve this problem. Thank you very much

**Comment by cgreening** [comment]
Sorry, this repo needs some proper instructions.

You need to run two copies of the throughput test, one transmitting and one receiving (or both transmitting and receiving if you want to test duplex throughput).

In the `main.cpp` line 120 can be uncommented - this will cause the device you are running it on to transmit as fast as it can.

There's also a log message you can uncomment on line 127 to see what rate it's sending at.

So, you need a transmitting device - which will blast packets out, and a receiving device that will receive the packets.

Hope that makes sense!

**Comment by hoangducnghi2207** [comment]
Thank you very much, i've solved this problem, Your test  is very useful for me

**Comment by hoangducnghi2207** [comment]
> Sorry, this repo needs some proper instructions.
> 
> You need to run two copies of the throughput test, one transmitting and one receiving (or both transmitting and receiving if you want to test duplex throughput).
> 
> In the `main.cpp` line 120 can be uncommented - this will cause the device you are running it on to transmit as fast as it can.
> 
> There's also a log message you can uncomment on line 127 to see what rate it's sending at.
> 
> So, you need a transmitting device - which will blast packets out, and a receiving device that will receive the packets.
> 
> Hope that makes sense!

Thank you very much, i've solved this problem, Your test is very useful for me

**Comment by cgreening** [comment]
Great! Glad it was useful.
